--liquibase formated sql

--changeset scholanova:1
CREATE TABLE IF NOT EXISTS MESSAGE(
    id NUMERIC NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE MESSAGE DROP COLUMN ID;
ALTER TABLE MESSAGE ADD COLUMN ID SERIAL PRIMARY KEY;